on:
  push:
    branches:
      - master

name: Integration Test

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Print current build ID
      run: |
        echo Integration test run: BUILD_ID

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Deploy Amazon ECS task definition
      uses: piradeepk/amazon-ecs-deploy-task-definition@34b80dfb0548c2ff537572a542a96a22aa270b34
      with:
        task-definition: task-definition.json
        service: sample-app-service
        cluster: default
        wait-for-service-stability: true
